name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check

  macos:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
